[package]
edition = "2024"
name = "shepherd-3"
version = "0.1.0"

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
embassy-embedded-hal.workspace = true
embassy-executor.workspace = true
embassy-stm32 = { workspace = true }
embassy-sync.workspace = true
embassy-time.workspace = true
embassy-futures.workspace = true
embedded-hal-async.workspace = true
embedded-hal-bus.workspace = true
heapless.workspace = true
panic-probe.workspace = true
assign-resources.workspace = true
#static_cell.workspace = true

function_name = { version = "0.3.0" }
variant_count = { version = "1.2.1" }

adbms6830b = { git = "https://github.com/bjackson312006/firmware-rs.git", rev = "0e0fab18e415c50ad90b85f9271faada0ca10ed0", features = ["defmt"] }
